/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#e5e2e1",
        secondary: "#ffb4aa",
        "surface-container-lowest": "#0e0e0e",
        "on-error": "#690005",
        "on-surface": "#e5e2e1",
        "on-primary-fixed": "#001d33",
        "surface-dim": "#131313",
        primary: "#98cbff",
        "secondary-fixed-dim": "#ffb4aa",
        "inverse-on-surface": "#313030",
        "tertiary-container": "#20b500",
        "on-tertiary-fixed-variant": "#095300",
        "surface-container-highest": "#353534",
        "surface-tint": "#98cbff",
        "surface-container": "#201f1f",
        "surface-container-low": "#1c1b1b",
        "on-secondary-fixed-variant": "#930005",
        "inverse-surface": "#e5e2e1",
        "inverse-primary": "#00629d",
        "primary-container": "#00a3ff",
        "on-surface-variant": "#bec7d4",
        "tertiary-fixed-dim": "#2ae500",
        "on-primary-fixed-variant": "#004a77",
        "on-tertiary": "#053900",
        "on-tertiary-fixed": "#022100",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#00375a",
        "surface-variant": "#353534",
        "surface-container-high": "#2a2a2a",
        "tertiary-fixed": "#79ff5b",
        outline: "#88919d",
        surface: "#131313",
        "on-tertiary-container": "#053d00",
        "on-secondary-fixed": "#410001",
        "secondary-container": "#c5020b",
        "outline-variant": "#3f4852",
        "surface-bright": "#3a3939",
        error: "#ffb4ab",
        background: "#131313",
        "on-secondary-container": "#ffd2cc",
        "primary-fixed": "#cfe5ff",
        "primary-fixed-dim": "#98cbff",
        tertiary: "#2ae500",
        "error-container": "#93000a",
        "on-secondary": "#690003",
        "on-primary": "#003354",
        "secondary-fixed": "#ffdad5",
      },
      fontFamily: {
        headline: ["Space Grotesk", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}
