<<<<<<< codesentinel/security-fixes
```python
@router.post("/pr", dependencies=[Depends(auth_required)])
=======
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from pydantic import BaseModel
import uuid
import json

from db.database import get_db
from models.scan import Scan
from config import settings

router = APIRouter()


class PRRequest(BaseModel):
    scan_id: str
    repo_url: str
    branch_name: str = "codesentinel/security-fixes"


@router.post("/pr")
>>>>>>> main
async def create_pull_request(request: PRRequest, db: AsyncSession = Depends(get_db)):
    # Token comes from server env — never from the client
    if not settings.GITHUB_TOKEN:
        raise HTTPException(400, "GITHUB_TOKEN not configured on server")

    result = await db.execute(select(Scan).where(Scan.id == request.scan_id))
    scan = result.scalar_one_or_none()
    if not scan:
        raise HTTPException(404, "Scan not found")

    patches_data = scan.patches_data
    if isinstance(patches_data, str):
        patches_data = json.loads(patches_data)

<<<<<<< codesentinel/security-fixes
    from github import Github
```
=======
    if not patches_data:
        raise HTTPException(400, "No patches available for this scan")

    try:
        from github import Github
        g = Github(settings.GITHUB_TOKEN)

        repo_path = request.repo_url.replace("https://github.com/", "").rstrip("/")
        repo = g.get_repo(repo_path)
        default_branch = repo.default_branch
        source = repo.get_branch(default_branch)

        # Create branch
        try:
            repo.create_git_ref(
                ref=f"refs/heads/{request.branch_name}",
                sha=source.commit.sha,
            )
        except Exception:
            pass  # Branch already exists

        # Apply validated patches
        applied = []
        for patch in patches_data:
            if not patch.get("validated"):
                continue
            try:
                file_path = patch["file_path"]
                patched_code = patch["patched_code"]
                try:
                    contents = repo.get_contents(file_path, ref=request.branch_name)
                    repo.update_file(
                        path=file_path,
                        message=f"fix(security): patch {patch.get('vuln_type', 'vulnerability')} in {file_path}",
                        content=patched_code,
                        sha=contents.sha,
                        branch=request.branch_name,
                    )
                except Exception:
                    repo.create_file(
                        path=file_path,
                        message=f"fix(security): patch {file_path}",
                        content=patched_code,
                        branch=request.branch_name,
                    )
                applied.append(file_path)
            except Exception as e:
                print(f"Patch apply failed for {patch.get('file_path')}: {e}")
                continue

        # Build PR description
        findings_data = scan.findings_data
        if isinstance(findings_data, str):
            findings_data = json.loads(findings_data)

        findings_summary = "\n".join(
            f"- [{f.get('severity','').upper()}] {f.get('title','')} — `{f.get('file_path','')}:{f.get('line_number','')}`"
            for f in (findings_data or [])[:15]
        )

        pr_body = f"""## 🛡️ CodeSentinel — Automated Security Report

**Security Score:** {scan.score_before or '?'} → **{scan.score_after or '?'} / 100**

### Vulnerabilities Fixed
{findings_summary}

### Patches Applied
{len(applied)} file(s) patched and verified by red agent.

### Exploit Chains
{len(json.loads(scan.chains_data) if isinstance(scan.chains_data, str) else (scan.chains_data or []))} multi-step vulnerability chains resolved.

---
*Generated by [CodeSentinel](https://github.com/NITHINKR06/codesentinel) — Automated Security Analysis*
"""

        pr = repo.create_pull(
            title="[CodeSentinel] Automated Security Fixes",
            body=pr_body,
            head=request.branch_name,
            base=default_branch,
        )

        # Save PR info
        scan.pr_url = pr.html_url
        scan.pr_number = pr.number
        db.add(scan)
        await db.commit()

        return {
            "pr_url": pr.html_url,
            "pr_number": pr.number,
            "files_patched": applied,
        }

    except Exception as e:
        raise HTTPException(500, f"Failed to create PR: {str(e)}")
>>>>>>> main
