from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from pydantic import BaseModel
import uuid

from db.database import get_db
from models.scan import Scan

router = APIRouter()


class PRRequest(BaseModel):
    scan_id: str
    github_token: str
    repo_url: str
    branch_name: str = "codesentinel/security-fixes"


@router.post("/pr")
async def create_pull_request(request: PRRequest, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Scan).where(Scan.id == uuid.UUID(request.scan_id)))
    scan = result.scalar_one_or_none()
    if not scan:
        raise HTTPException(404, "Scan not found")

    if not scan.patches_data:
        raise HTTPException(400, "No patches available for this scan")

    from github import Github
    g = Github(request.github_token)

    # Parse repo from URL
    repo_path = request.repo_url.replace("https://github.com/", "").rstrip("/")
    repo = g.get_repo(repo_path)

    default_branch = repo.default_branch
    source = repo.get_branch(default_branch)

    # Create new branch
    try:
        repo.create_git_ref(
            ref=f"refs/heads/{request.branch_name}",
            sha=source.commit.sha,
        )
    except Exception:
        pass  # Branch may already exist

    # Apply patches as commits
    applied = []
    for patch in scan.patches_data:
        if not patch.get("validated"):
            continue
        try:
            file_path = patch["file_path"]
            try:
                contents = repo.get_contents(file_path, ref=request.branch_name)
                repo.update_file(
                    path=file_path,
                    message=f"fix: security patch for {patch.get('vuln_type', 'vulnerability')} in {file_path}",
                    content=patch["patched_code"],
                    sha=contents.sha,
                    branch=request.branch_name,
                )
            except Exception:
                repo.create_file(
                    path=file_path,
                    message=f"fix: security patch in {file_path}",
                    content=patch["patched_code"],
                    branch=request.branch_name,
                )
            applied.append(file_path)
        except Exception as e:
            continue

    # Build PR body
    findings_summary = "\n".join(
        f"- [{f.get('severity','').upper()}] {f.get('title','')}" 
        for f in (scan.findings_data or [])[:10]
    )
    pr_body = f"""## CodeSentinel Security Report

**Score:** {scan.score_before or '?'} → {scan.score_after or '?'} / 100

### Findings Fixed ({len(applied)} patches applied)
{findings_summary}

### Chains Detected
{len(scan.chains_data or [])} multi-step vulnerability chains resolved.

### Ghost Commits
{len(scan.ghost_commits_data or [])} historical secret leaks found and documented.

---
*Generated by [CodeSentinel](https://github.com/your-org/codesentinel)*
"""

    pr = repo.create_pull(
        title="[CodeSentinel] Automated Security Fixes",
        body=pr_body,
        head=request.branch_name,
        base=default_branch,
    )

    # Persist PR info
    scan.pr_url = pr.html_url
    scan.pr_number = pr.number
    db.add(scan)
    await db.commit()

    return {
        "pr_url": pr.html_url,
        "pr_number": pr.number,
        "files_patched": applied,
    }
